/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY genColors.js.
 *
 * DO NOT MANUALLY MODIFY THIS FILE.
 */

enum BackgroundColorClass {
  BackgroundOverlay = "backgroundColorBackgroundOverlay",
  BeigeDark = "backgroundColorBeigeDark",
  BeigeLight = "backgroundColorBeigeLight",
  Dimmer = "backgroundColorDimmer",
  Navy = "backgroundColorNavy",
  NavyHover = "backgroundColorNavyHover",
  Pink = "backgroundColorPink",
  Rust = "backgroundColorRust",
  WinterGreen = "backgroundColorWinterGreen",
  Yellow = "backgroundColorYellow",
}

export default BackgroundColorClass;
