/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY genColors.js.
 *
 * DO NOT MANUALLY MODIFY THIS FILE.
 */

enum ColorValue {
  BackgroundOverlay = "var(--color-backgroundOverlay)",
  BeigeDark = "var(--color-beigeDark)",
  BeigeLight = "var(--color-beigeLight)",
  Dimmer = "var(--color-dimmer)",
  Navy = "var(--color-navy)",
  NavyHover = "var(--color-navyHover)",
  Pink = "var(--color-pink)",
  Rust = "var(--color-rust)",
  WinterGreen = "var(--color-winterGreen)",
  Yellow = "var(--color-yellow)",
}

export default ColorValue;
